version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    environment:
      - POSTGRES_DB=next-auth-sandbox
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=appuser
      - TZ=UTC
    volumes:
      - ./postgres:/var/lib/postgresql/data
